"""init devices, users and likes tables

Revision ID: 5c25bf16d9bc
Revises: d399a1282d29
Create Date: 2026-09-23 12:36:35.153105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c25bf16d9bc'
down_revision: Union[str, Sequence[str], None] = 'd399a1282d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_device', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id_device'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_device')
    )
    op.drop_table('applications')
    op.add_column('devices', sa.Column('id_user', sa.Integer(), nullable=False))
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.create_foreign_key(None, 'devices', 'users', ['id_user'], ['id_user'])
    op.drop_column('devices', 'is_deleted')
    op.drop_column('devices', 'creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('creator', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.alter_column('devices', 'status',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_column('devices', 'id_user')
    op.create_table('applications',
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_device', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id_device'], name=op.f('applications_id_device_fkey')),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name=op.f('applications_id_user_fkey')),
    sa.PrimaryKeyConstraint('id_user', 'id_device', name=op.f('applications_pkey'))
    )
    op.drop_table('likes')
    # ### end Alembic commands ###
