"""device add date_completed

Revision ID: c5392c6dca5a
Revises: ee1dbbb48534
Create Date: 2026-10-04 09:14:15.224951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5392c6dca5a'
down_revision: Union[str, Sequence[str], None] = 'ee1dbbb48534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('date_completed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_likes_id_like'), 'likes', ['id_like'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id_like'), table_name='likes')
    op.drop_column('devices', 'date_completed')
    # ### end Alembic commands ###
