"""init devices, users and applications tables

Revision ID: d399a1282d29
Revises: 
Create Date: 2026-09-22 04:03:24.498398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd399a1282d29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id_device', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=9), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('power', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('resistance', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('creator', sa.String(length=50), nullable=False),
    sa.Column('date_formed', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_device')
    )
    op.create_index(op.f('ix_devices_id_device'), 'devices', ['id_device'], unique=False)
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('applications',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_device', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id_device'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_device')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_id_device'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
