"""like add id_like pk

Revision ID: ee1dbbb48534
Revises: d399a1282d29
Create Date: 2026-10-04 01:25:51.750549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1dbbb48534'
down_revision: Union[str, Sequence[str], None] = 'd399a1282d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("likes")
    op.create_table(
        "likes",
        sa.Column("id_like", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("id_user", sa.Integer(), sa.ForeignKey("users.id_user"), nullable=False),
        sa.Column("id_device", sa.Integer(), sa.ForeignKey("devices.id_device"), nullable=False),
        sa.UniqueConstraint("id_user", "id_device"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_index(op.f('ix_likes_id_like'), table_name='likes')
    op.drop_column('likes', 'id_like')
    # ### end Alembic commands ###
